### ISSUE TITLE
Run_Needles with matlab 2014b 

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/WGs#2]
I set up the toolbox jsonlab-master by adding it to the matlab path, and did the rest of the setup following the guideline. But meet this error:
```

>> Run_Needles
Error using image
Incorrect number of arguments specified

Error in Needles>Needles_OutputFcn (line 29)
h.im_logo = image(h.axes_logo, logo);

Error in gui_mainfcn (line 264)
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in Needles (line 16)
    gui_mainfcn(gui_State, varargin{:});

Error in Run_Needles (line 7)
Needles
 
```

**Comment by oliche** [comment]
Fixed in f4017d555cf3e6a16adb530343f49f710afed5e0
This is an unsupported version, you may run into issues that won't be fixeable like this one
